<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>straznik</AssemblyName>
    <RootNamespace>Straznik.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Straznik.Core\Straznik.Core.csproj" />
  </ItemGroup>

</Project>
